behaviors:
  BasicMoreComplex:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256               # plus stable
      buffer_size: 4096             # plus de données avant update
      learning_rate: 0.0001         # apprentissage plus fin
      beta: 0.002                   # moins de régularisation
      epsilon: 0.1                  # exploration moins agressive
      lambd: 0.97                   # meilleur advantage estimate
      num_epoch: 6                  # un peu plus d'update par batch
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128             # réseau un peu plus costaud
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99                # plus long terme
        strength: 1.0

    behavioral_cloning:
      demo_path: Demos/BasicMoreComplex/Demo.demo #,Demos/Demo2.demo,Demos/Demo3.demo   plusieurs démos variés
      strength: 0.8               # copie assez fort au début
      steps: 200000               # imitation active pendant 200k steps

    keep_checkpoints: 10
    max_steps: 2000000             # laisse-le apprendre longtemps
    time_horizon: 64
    summary_freq: 2000             # log régulier






  BasicSensor:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256               # plus stable
      buffer_size: 4096             # plus de données avant update
      learning_rate: 0.0001         # apprentissage plus fin
      beta: 0.002                   # moins de régularisation
      epsilon: 0.1                  # exploration moins agressive
      lambd: 0.97                   # meilleur advantage estimate
      num_epoch: 6                  # un peu plus d'update par batch
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128             # réseau un peu plus costaud
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99                # plus long terme
        strength: 1.0

    behavioral_cloning:
      demo_path: Demos/BasicSensor/Demo.demo #,Demos/Demo2.demo,Demos/Demo3.demo   plusieurs démos variés
      strength: 0.8               # copie assez fort au début
      steps: 200000               # imitation active pendant 200k steps

    keep_checkpoints: 10
    max_steps: 2000000             # laisse-le apprendre longtemps
    time_horizon: 64
    summary_freq: 2000             # log régulier





  BasicSensorCooperative:
    trainer_type: poca
    hyperparameters:
      batch_size: 512             # plus stable
      buffer_size: 8192
      learning_rate: 0.0003       # un peu plus rapide
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear

    network_settings:
      normalize: true             # meilleure stabilité
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    # behavioral_cloning:
    #   demo_path: Demos/BasicSensorCooperative/Demo_1.demo
    #   strength: 0.5              # réduit un peu pour laisser le RL s'exprimer
    #   steps: 150000

    keep_checkpoints: 10
    max_steps: 3000000
    time_horizon: 128
    summary_freq: 10000
