behaviors:
  Hunter:
    trainer_type: poca
    init_path: results\nouveau_phase1\Hunter\checkpoint.pt
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 768
      num_layers: 3
      vis_encode_type: simple
      encoding_size: 128
      # We add a RNN layers
      memory:
        sequence_length: 128
        memory_size: 512
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 20000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 4000
      window: 15
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0
  Prey:
    trainer_type: poca
    init_path: results\nouveau_phase2\Prey\checkpoint.pt
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
      encoding_size: 128
      # We add a RNN layers
      memory:
        sequence_length: 128
        memory_size: 512
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 1500
    summary_freq: 20000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 4000
      window: 15
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0