behaviors:
  Hunter:
    trainer_type: poca
    init_path: results\HunterPreyPOCARNN9_next_phase\Hunter\checkpoint.pt
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      encoding_size: 64
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 500
    summary_freq: 20000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 4000
      window: 15
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0

  Prey:
    trainer_type: poca
    init_path: results\HunterPreyPOCARNN9\Prey\checkpoint.pt
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      encoding_size: 64
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 500
    summary_freq: 20000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 4000
      window: 15
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0
